### ISSUE TITLE
iOS: Attempt to present ZXing_Mobile_AVCaptureScannerViewController on Xamarin_Forms_Platform_iOS_PlatformRenderer whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by mahgo** [Redth/ZXing.Net.Mobile#138]
AppNameiOS[1212:254550] Warning: Attempt to present <ZXing_Mobile_AVCaptureScannerViewController: 0x17f48b90> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x17966420> whose view is not in the window hierarchy!

This error is outputted when another view before this one has been presented modally. While presenting multiple views modally is probably not the best practice, it should still be possible.

Note: I am using Xamarin Forms and am using ZXing via dependency.

**Comment by charlenni** [comment]
Same here. I also used a modal NavigationPage and get the same error. Perhaps this http://stackoverflow.com/questions/11862883/whose-view-is-not-in-the-window-hierarchy is the same problem?

**Comment by aritchie** [comment]
@Redth - Despite what people say, using the keywindow or just passing in a navigation controller is incorrect.  These can change depending on the design of the app (ie. reset the root controller because you were logged out) or be in the background because of a modal window.  I have used this hunk of a hack with great success (and it continues to receive the occasional patch):

https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/UserDialogsImpl.cs#L330

It is also in use within acr.barcodes (which I'm hoping to deprecate now that you're PCL) as well and it does fix this issue.

**Comment by Redth** [comment]
@aritchie this is digging up the past, but is this what you're referring to?
https://github.com/aritchie/support/blob/master/Acr.Support.iOS/Extensions.cs#L29-L36

**Comment by aritchie** [comment]
@redth yup
