### ISSUE TITLE
Reference issue after 1.4.4 Xamarin Forms Update

### ISSUE THREAD

**Issue by jjohnnydotnet** [Redth/ZXing.Net.Mobile#188]
After updating to the latest Xamarin Forms 1.4.4 update my app fails to compile, when I try to just compile the IOS project I'm getting this error

/Users/JOHNNY_MAC/Desktop/MyApp/iOS/MTOUCH: Error MT2002: Failed to resolve assembly: 'zxing.ios, Version=0.14.0.0, Culture=neutral, PublicKeyToken=null' (MT2002) (MyApp.iOS)

It was compiling fine just before the update

**Comment by TorbenK** [comment]
got the same for iOS and android missing the monodroid equilavent

**Comment by aritchie** [comment]
It is probably because you updated everything, not just xamarin forms.  Sometimes, when you add new files to a nuget package, nuget doesn't (un)install these files.  Remove the entire package from your entire project and reinstall it.  Don't just try to run the nuget reinstall command as it won't help.

**Comment by Redth** [comment]
Yeah I think @aritchie is right.  The older version did reference the `zxing.ios` assembly however now it's been switched to use the `zxing.portable` assembly instead.  Uninstalling and reinstalling the package should do it.
