### ISSUE TITLE
NETPortable,Version=v4.5

### ISSUE THREAD

**Issue by attrib75** [Redth/ZXing.Net.Mobile#200]
HI,  I tried to install this into a new Xamarin Forms PCL project, and am getting this:

Could not install package 'ZXing.Net.Mobile 1.5.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework

Is there anything I can do to my PCL (downgrade) so that I can get this installed?  If not, do you know of how I can just use ZXing.NET natively on iOS and Android, by way of a dependency service?  thanks!

**Comment by brettcook99** [comment]
Hey attrib75,

Were you able to resolve this issue?  I'm having the same problem...

**Comment by attrib75** [comment]
Yes, I added the dll manually through 'add reference'.  This worked with another nuget package displaying the same error as well

**Comment by Redth** [comment]
Weird, not sure what's happening here.  Could someone post a project that exhibits this error?

**Comment by brettcook99** [comment]
Thanks attrib75, that did indeed solve the problem.

I think what is happening Redth, is that we need the PCL references is our portable code, however nuget refuses to import the library to the portable project since it's not flagged as compatible with .NETPortable.

If the library can be flagged to be compatible with .NETPortable, then people can import it to that part of their solution and gain the necessary references automatically.

**Comment by tfierens** [comment]
@attrib75  Which dll are you referring to? I'm having drastic problems trying to build my machine on a build server where .net is not installed and that's just one of the many errors I'm getting even though I've literarily installed every framework, multi-targeting pack, sdk, I can find. Hopefully, this will knock one out. Thanks.
