### ISSUE TITLE
Barcodes with different color than b/w

### ISSUE THREAD

**Issue by sadedil** [Redth/ZXing.Net.Mobile#210]
Hi;

I have a rare problem.
Our company have Code 39 barcodes, with **black bars on the red background**. ZXing barcode scanner can't read properly this barcodes, somtimes it takes 20 seconds, but reading OK for standart b/w barcodes, it reads in 1-2 second(s).

Is there any way to solve/hack this problem? Any configuration, suggestion or similar thing?

Platform: Xamarin Android

**Comment by Redth** [comment]
You could try setting the TryInverted option to true, however I believe that's more typically useful when the barcode is white bars on a dark background.

**Comment by sadedil** [comment]
Hi Redth, thanks for response.
I've tried but it didn't work, actually it worse then TryInverted = false.

Maybe i can investigate TryInverted implementation and add similar color correction functionality.

**Comment by sadedil** [comment]
I've tried a lot of things with PlanarYUVLuminanceSource, but can't make any progress.

**Comment by redwolf2** [comment]
Hardware Barcodescanner use a red light in order to illuminate the code. That way the scanner sees red like/similar to a white surface. Imageing the world through red glasses, you can't distinguish a letter written on red to a letter written on white in a Room with a Red light. That is the reason, why a green background instead of red is a no-go for Hardware Scanners.
When you have only the camera, and no red leds you will run into problems. Try to take a picture and remove all colours from it. That way you will see, what the scanner sees. It will probably be black bars on a dark, grey surface - bad contrast in order to read a code. You might need to implement a filter that ups the contrast of the picture, before it gets decoded.

**Comment by Redth** [comment]
Awesome explanation, and basically the answer is, this is out of scope of the project for now.  Some things are definitely just better with hardware scanners, this library isn't really meant to take their place.
