### ISSUE TITLE
Android - Automatically add required permissions 

### ISSUE THREAD

**Issue by jamesmontemagno** [Redth/ZXing.Net.Mobile#228]
Please add assembly level required permissions for Camera and Flashlight to the library. This will greatly reduce the number of developers running into issues.

Also, document the new permission requirements.

**Comment by Redth** [comment]
Flashlight is not required, and was fixed in #227 however it's probably wise to add the camera permission to the library.

**Comment by BStrat77** [comment]
While I understand the intention here I'm running into an issue where we want to have the camera scanner as an optional feature if the device has a camera, otherwise we can just use the IR scanner in the device (Zebra TC20 has two different models, one with a camera and one without). I cannot install on the device without the camera because of the camera Uses Permission attribute added. Any thoughts on how to get around this? Thanks!
