### ISSUE TITLE
ZXingScannerFragment - AutoFocus not working

### ISSUE THREAD

**Issue by eclipsed4utoo** [Redth/ZXing.Net.Mobile#296]
I am using the ZXingScannerFragment to show the barcode scanning camera preview in a small area at the bottom of the screen.

![scanning](https://cloud.githubusercontent.com/assets/1720293/14348549/3a141352-fc8b-11e5-88e0-a13a2c87ac6d.png)

I am essentially using a button to slide a FrameLayout into view, then replacing the FrameLayout with the fragment. I have also added double-tapping functionality to do auto-focus, which doesn't seem to work. The camera's resolution is being set to 1920x1080(max for the camera on my phone), but the camera preview is blurry.

I can't post all of the code, but here is the essential code that I am using...

        private void OpenScannerWithCamera()
	{
		if (_scanFragment == null)
		{
			_scanFragment = new ZXingScannerFragment();
		}

		Activity.SupportFragmentManager.BeginTransaction ()
			.Replace (Resource.Id.ActiveScannerFragmentContainer, _scanFragment)
			.Commit ();

		if (AndroidHelpers.IsMarshmallow)
		{
			GetCameraPermissionAsync();
		}
		else
		{
			StartScanning();
		}
	}

	private void StartScanning()
	{
		var options = new MobileBarcodeScanningOptions
			{
				PossibleFormats = new List<ZXing.BarcodeFormat> {
					ZXing.BarcodeFormat.CODE_39, ZXing.BarcodeFormat.CODE_128
				},
				CameraResolutionSelector = availableResolutions => {

					foreach (var ar in availableResolutions) {
						Console.WriteLine ("Resolution: " + ar.Width + "x" + ar.Height);
					}
					return availableResolutions[0];
				}
			};

		_scanFragment.CustomOverlayView = null;
		_scanFragment.UseCustomOverlayView = true;

		_scanFragment.StartScanning(result =>
			{
				// code for processing scan
			}, options); 

		StartAutoFocus();
	}

	private void StartAutoFocus()
	{
		if (_scanFragment == null)
		{
			return;
		}

		Task.Run(async () =>
			{
				await Task.Delay(1500);
				this.Activity.RunOnUiThread(() => _scanFragment.AutoFocus());
			});
	}

Then auto focus...

	private void ViewDoubleTapped (object sender, GestureDetector.DoubleTapEventArgs e)
	{
		_scanFragment.AutoFocus();
	}

Not sure what I am doing wrong to get the auto focus to work. The ViewDoubleTapped event is getting fired.

Any thoughts or help?

**Comment by mulflar** [comment]
By using:
` return availableResolutions[0];`
You are calling the lowest of the posible camera resolution's
Thats why you see it blurry, try with 
` return null;`
To leave it unmanaged or 
` return availableResolutions[availableResolutions.Count-1];`
To get the last of the array, I'm currently trying to make a resolution selector for my app...

**Comment by eclipsed4utoo** [comment]
I've tried removing that code completely and just having the library choose the best resolution(which it will do), and that didn't work either. I've also tried using the highest resolution(1920x1080), and that didn't work either.

**Comment by mulflar** [comment]
What about ZXingScannerFragment class? 
I'm using this one https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Android/ZXingScannerFragment.cs (except a little change on line 33, and using Android.App instead of using Android.Support.V4.App and for me it directly works with autofocus without any need of any function like your StartAutoFocus()

**Comment by mulflar** [comment]
That's my code of the scann function:
` void scan()
        {
            try
            {
                opts.AutoRotate = false;
                opts.TryInverted = false;
                opts.UseNativeScanning = true;
                opts.PureBarcode = true;
                opts.UseFrontCameraIfAvailable = false;
                opts.TryHarder = false;

                scanFragment.StartScanning(result => {
                    if (result == null || string.IsNullOrEmpty(result.Text)) {
                        Toast.MakeText(this, "Scanning Cancelled", ToastLength.Long).Show();
                        return;
                    }
                    else
                    {
                       //DO STUFF
                    }
                }, opts);
            }
            catch(Exception ex)
            {
                Insights.Report(ex);
            }
        }`

I

**Comment by bwwilliam** [comment]
Hi Ryan,
Have you got the problem solved? 
I am having exactly same issue. it would be really appreciated if you can share some ideas. Thank you.
Please see the link below.
http://stackoverflow.com/questions/37295838/zxing-camera-becomes-slow-when-calling-startscanning-second-time-in-xamarin

**Comment by Redth** [comment]
FYI, PR #361 should really improve autofocus on android.

**Comment by alexsandro-xpt** [comment]
Still not working...

**Comment by Myndale** [comment]
Still not working here either. I'm using the current version on NuGet (i.e. v2.1.47), note the huge difference between the ZXing preview and the built-in camera preview: http://imgur.com/xvxHo61. It's a real shame too, because it's great lib and very easy to use etc but this issue renders it unusable.

**Comment by Myndale** [comment]
Quick follow-up....this seems to be related to camera initialization. When I run my app the image is usually very blurry, as shown in the image I posted above. But if I run the native camera app first, then run my app immediately afterwards, the image is crystal clear. It's as if the camera app's initialization is doing something to switch the capture into high-res mode or something, and it somehow persists after that app is closed. Could the camera app be somehow telling the OS to purge cached resources or something in order to free up memory?

**Comment by spurdow** [comment]
Im having the same issue. Currently using 2.2.9

**Comment by alexsandro-xpt** [comment]
Are you test the last 2.3.1 version?
