### ISSUE TITLE
Compile against Xamarin.Forms >= 2.3?

### ISSUE THREAD

**Issue by SarSars** [Redth/ZXing.Net.Mobile#357]
Hi there,

Would it be possible to get a release of ZXing.Net.Mobile for Xamarin.Forms that's compiled against version 2.3.0.49 or higher?  It would be very helpful!

Thanks,

Peter.

**Comment by inkrh** [comment]
Also having a similar issue using X.F in adding ZXing.Net.Mobile and ZXing.Net.Mobile.Forms on the Android side -  apparently X.F. 2.3.0.107 also installs a newer Xamarin.Android.Support (v23.3.0?), which the ZXing.Net.Mobile.Forms requires to be == 23.0.1.3 rather than >= 23.0.1.3, so the Xamarin.Android.Support required by the current Xamarin.Forms blocks installation?


<img width="568" alt="screen shot 2016-07-06 at 12 57 18" src="https://cloud.githubusercontent.com/assets/16457014/16629044/e7d34b4a-4379-11e6-8ce6-a069a436068c.png">

**Comment by inkrh** [comment]
Moving my comment to a new issue since it is a different problem.

**Comment by Redth** [comment]
Also, this is now in master, will be released soon (compiling against >= Xamarin.Forms 2.3.x)

**Comment by SarSars** [comment]
Great, thank you!
