### ISSUE TITLE
app crushes with illegal state exception

### ISSUE THREAD

**Issue by umairali612** [Redth/ZXing.Net.Mobile#394]
java.lang.illegalstateexception: cannot perform this task after onsaveinstancestate 
Barcode was found but app crashes with above exception.

**Comment by Redth** [comment]
Going to need a lot more info...

**Comment by Lapinou42** [comment]
I got this exception when I want to show a fragment from the scanner activity.
I tried many things like : 
- Try with CommitAllowingStateLoss();
- Try to override the method protected override void OnSaveInstanceState(Bundle outState) but without calling super

And when I do these things, I have another exception that said: the activity has been destroyed.

I'm so sad because no QRcode has recognize when I use a fragment (only activity works) but I got this exception because I want to show a Dialogfragment when a wrong QRcode is recognized.
