### ISSUE TITLE
Slow to Recognize Barcode Mostly in iOS

### ISSUE THREAD

**Issue by EnGlamdring** [Redth/ZXing.Net.Mobile#411]
We're using the plugin found in Xamarin. 

https://www.nuget.org/packages/ZXing.Net.Mobile

Many of our users are discovering that the camera is slow to pick up barcodes in comparison to the apps on iOS devices. Is this a known issue? What can I do to fix it?

Some users complain on Android as well but not enough for me to think the problem exists in both places. Just wondering if there is a way to optimize the code or implementation.

**Comment by Spierki** [comment]
+1

**Comment by redwolf2** [comment]
The slower in field scan performance of zxing in general is due to the inability to read blurry codes. All codes must be in camera focus in order to get a decode result. Zxing is also not rotation aware. It will not decode a 45° rotated barcode. There is no way to optimize it, other than providing a working object detection.
To get those detection going, deep mathematical knowledge and know-how is required. Here is an example of what it takes:
https://www.ma.utexas.edu/users/rward/barcode

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
