### ISSUE TITLE
Crashing on Nexus 9 tablet on App startup

### ISSUE THREAD

**Issue by jovymathew** [Redth/ZXing.Net.Mobile#494]
I have a Nexus 9 tablet where the app crashes on startup after working on the app and then closing and restarting the app.  See stacktrace below.

I am using ZXing for Xamarin Forms version 2.1.47

Is there any workarounds for this issue?

01-06 14:39:26.281: E/mono-rt(4339): Stacktrace:
01-06 14:39:26.281: E/mono-rt(4339):   at <unknown> <0xffffffff>
01-06 14:39:26.281: E/mono-rt(4339):   at System.Array.SortImpl<TKey_REF> (TKey_REF[],int,int,System.Collections.Generic.IComparer`1<TKey_REF>) <0x00653>
01-06 14:39:26.282: E/mono-rt(4339):   at System.Array.Sort<T_REF> (T_REF[],int,int,System.Collections.Generic.IComparer`1<T_REF>) <0x00063>
01-06 14:39:26.282: E/mono-rt(4339):   at System.Collections.Generic.List`1<T_REF>.Sort (int,int,System.Collections.Generic.IComparer`1<T_REF>) <0x0008b>
01-06 14:39:26.282: E/mono-rt(4339):   at System.Collections.Generic.List`1<T_REF>.Sort (System.Collections.Generic.IComparer`1<T_REF>) <0x00033>
01-06 14:39:26.282: E/mono-rt(4339):   at Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables (System.Globalization.CultureInfo,Mono.Globalization.Unicode.TailoringInfo,Mono.Globalization.Unicode.Contraction[]&,Mono.Globalization.Unicode.Level2Map[]&) <0x0043f>
01-06 14:39:26.282: E/mono-rt(4339):   at Mono.Globalization.Unicode.SimpleCollator..ctor (System.Globalization.CultureInfo) <0x0016f>
01-06 14:39:26.282: E/mono-rt(4339):   at Mono.Globalization.Unicode.SimpleCollator..cctor () <0x0005b>
01-06 14:39:26.282: E/mono-rt(4339):   at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0x0006f>
01-06 14:39:26.282: E/mono-rt(4339):   at <unknown> <0xffffffff>
01-06 14:39:26.282: E/mono-rt(4339):   at System.Globalization.CompareInfo.GetCollator () <0x00147>
01-06 14:39:26.282: E/mono-rt(4339):   at System.Globalization.CompareInfo.IsPrefix (string,string,System.Globalization.CompareOptions) <0x000f3>
01-06 14:39:26.282: E/mono-rt(4339):   at string.StartsWith (string,System.StringComparison) <0x000b3>
01-06 14:39:26.282: E/mono-rt(4339):   at string.StartsWith (string) <0x0002b>
01-06 14:39:26.282: E/mono-rt(4339):   at System.TimeZoneInfo/AndroidTimeZones.GetTimeZone (string,string) <0x000cf>
01-06 14:39:26.282: E/mono-rt(4339):   at System.TimeZoneInfo/AndroidTimeZones.get_Local () <0x00013>
01-06 14:39:26.282: E/mono-rt(4339):   at System.TimeZoneInfo.CreateLocal () <0x00007>
01-06 14:39:26.282: E/mono-rt(4339):   at System.TimeZoneInfo.get_Local () <0x00023>
01-06 14:39:26.282: E/mono-rt(4339):   at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc (System.DateTime,bool&) <0x0002b>
01-06 14:39:26.282: E/mono-rt(4339):   at System.DateTime.get_Now () <0x0006f>
01-06 14:39:26.282: E/mono-rt(4339):   at ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer.Init () <0x0000f>
01-06 14:39:26.282: E/mono-rt(4339):   at ZXing.Net.Mobile.Forms.Android.Platform.Init () <0x00007>
01-06 14:39:26.282: E/mono-rt(4339):   at MobileX.Droid.MainApplication.OnCreate () <0x0003b>
01-06 14:39:26.282: E/mono-rt(4339):   at Android.App.Application.n_OnCreate (intptr,intptr) <0x00037>
01-06 14:39:26.282: E/mono-rt(4339):   at (wrapper dynamic-method) object.37840c32-565b-4512-970b-31e4fe92cd96 (intptr,intptr) <0x0003b>
01-06 14:39:26.282: E/mono-rt(4339):   at (wrapper native-to-managed) object.37840c32-565b-4512-970b-31e4fe92cd96 (intptr,intptr) <0x000ab>
01-06 14:39:26.283: E/mono-rt(4339): Attempting native Android stacktrace:
01-06 14:39:26.286: E/mono-rt(4339): 	Could not unwind with `libunwind.so`: dlopen failed: library "/data/app/com.ups.mobile.android-1/lib/arm/libunwind.so" not found
01-06 14:39:26.286: E/mono-rt(4339): 	Could not unwind with `libcorkscrew.so`: dlopen failed: library "/data/app/com.ups.mobile.android-1/lib/arm/libcorkscrew.so" not found
01-06 14:39:26.286: E/mono-rt(4339): 	No options left to get a native stacktrace :-(
01-06 14:39:26.286: E/mono-rt(4339): =================================================================
01-06 14:39:26.286: E/mono-rt(4339): Got a SIGSEGV while executing native code. This usually indicates
01-06 14:39:26.286: E/mono-rt(4339): a fatal error in the mono runtime or one of the native libraries 
01-06 14:39:26.286: E/mono-rt(4339): used by your application.
01-06 14:39:26.286: E/mono-rt(4339): =================================================================
01-06 14:39:26.286: A/libc(4339): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 4339 (.mobile.android)

**Comment by pgokul** [comment]
Were you able to find any workaround for this?
We are also facing the same issue with a similar call stack

04-06 06:15:16.543 15807 15807 E mono-rt : Stacktrace:
04-06 06:15:16.543 15807 15807 E mono-rt :
04-06 06:15:16.543 15807 15807 E mono-rt :   at <unknown> <0xffffffff>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.AndroidTzData.GetTimeZoneData (string) <0x00043>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo/AndroidTimeZones._GetTimeZone (string,string) <0x00053>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo/AndroidTimeZones.GetTimeZone (string,string) <0x0014f>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo/AndroidTimeZones.get_Local () <0x00013>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo.CreateLocal () <0x00007>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo.get_Local () <0x00023>
04-06 06:15:16.543 15807 15807 E mono-rt :   at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc (System.DateTime,bool&) <0x0002b>
04-06 06:15:16.544 15807 15807 E mono-rt :   at System.DateTime.get_Now () <0x0006f>
04-06 06:15:16.544 15807 15807 E mono-rt :   at ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer.Init () <0x0000f>
04-06 06:15:16.544 15807 15807 E mono-rt :   at ZXing.Net.Mobile.Forms.Android.Platform.Init () <0x00007>
04-06 06:15:16.544 15807 15807 E mono-rt :   at TestApp.Droid.MainActivity.OnCreate (Android.OS.Bundle) <0x0002b>
04-06 06:15:16.544 15807 15807 E mono-rt :   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x0005b>
04-06 06:15:16.544 15807 15807 E mono-rt :   at (wrapper dynamic-method) object.d0d58d99-6903-4b36-a09b-93eef8f211e1 (intptr,intptr,intptr) <0x00043>
04-06 06:15:16.544 15807 15807 E mono-rt :   at (wrapper native-to-managed) object.d0d58d99-6903-4b36-a09b-93eef8f211e1 (intptr,intptr,intptr) <0x000b3>
04-06 06:15:16.544 15807 15807 E mono-rt :
04-06 06:15:16.544 15807 15807 E mono-rt : Attempting native Android stacktrace:
04-06 06:15:16.544 15807 15807 E mono-rt :
04-06 06:15:16.546 15807 15807 E mono-rt :      Could not unwind with `libunwind.so`: dlopen failed: library "/data/app/TestApp-1/lib/arm/libunwind.so" not found
04-06 06:15:16.546 15807 15807 E mono-rt :      Could not unwind with `libcorkscrew.so`: dlopen failed: library "/data/app/TestApp-1/lib/arm/libcorkscrew.so" not found
04-06 06:15:16.547 15807 15807 E mono-rt :
04-06 06:15:16.547 15807 15807 E mono-rt :      No options left to get a native stacktrace :-(
04-06 06:15:16.547 15807 15807 E mono-rt :
04-06 06:15:16.547 15807 15807 E mono-rt : =================================================================
04-06 06:15:16.547 15807 15807 E mono-rt : Got a SIGSEGV while executing native code. This usually indicates
04-06 06:15:16.547 15807 15807 E mono-rt : a fatal error in the mono runtime or one of the native libraries
04-06 06:15:16.547 15807 15807 E mono-rt : used by your application.
04-06 06:15:16.547 15807 15807 E mono-rt : =================================================================
04-06 06:15:16.547 15807 15807 E mono-rt :
04-06 06:15:16.547 15807 15807 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 15807 (.TestApp)
04-06 06:15:16.547   187   187 W         : debuggerd: handling request: pid=15807 uid=10097 gid=10097 tid=15807
04-06 06:15:16.613 15824 15824 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 06:15:16.614 15824 15824 F DEBUG   : Build fingerprint: 'google/volantis/flounder:7.1.1/NMF26F/3425388:user/release-keys'
04-06 06:15:16.614 15824 15824 F DEBUG   : Revision: '0'
04-06 06:15:16.614 15824 15824 F DEBUG   : ABI: 'arm'
04-06 06:15:16.614 15824 15824 F DEBUG   : pid: 15807, tid: 15807, name: .TestApp  >>> TestApp <<<
04-06 06:15:16.614 15824 15824 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
04-06 06:15:16.614 15824 15824 F DEBUG   :     r0 cb9e8f60  r1 00004001  r2 00000000  r3 cb9e8f70
04-06 06:15:16.614 15824 15824 F DEBUG   :     r4 00000008  r5 e08ee27c  r6 00001f3c  r7 00000014
04-06 06:15:16.614 15824 15824 F DEBUG   :     r8 00001f38  r9 00000014  sl cb9e8f60  fp ffc848f0
04-06 06:15:16.614 15824 15824 F DEBUG   :     ip e08ee2c0  sp ffc848c0  lr e071e2fc  pc e0690a60  cpsr 800b0010
04-06 06:15:16.615 15824 15824 F DEBUG   :
04-06 06:15:16.615 15824 15824 F DEBUG   : backtrace:
04-06 06:15:16.615 15824 15824 F DEBUG   :     #00 pc 000dda60  /data/app/TestApp-1/lib/arm/libmonosgen-2.0.so
04-06 06:15:16.812   615 15825 W ActivityManager:   Force finishing activity TestApp/md5e91def38f862194d4028772de9f25d90.MainActivity
04-06 06:15:16.820   187   187 W         : debuggerd: resuming target 15807
04-06 06:15:16.823   615   642 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
04-06 06:15:16.825   615 15825 W ActivityManager: Exception thrown during pause
04-06 06:15:16.825   615 15825 W ActivityManager: android.os.DeadObjectException
04-06 06:15:16.825   615 15825 W ActivityManager:       at android.os.BinderProxy.transactNative(Native Method)
04-06 06:15:16.825   615 15825 W ActivityManager:       at android.os.BinderProxy.transact(Binder.java:615)
04-06 06:15:16.825   615 15825 W ActivityManager:       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:785)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1141)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3523)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3359)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13429)
04-06 06:15:16.825   615 15825 W ActivityManager:       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
04-06 06:15:16.827   199   199 E lowmemorykiller: Error writing /proc/15807/oom_score_adj; errno=22
04-06 06:15:16.828   615 15825 I WindowManager: Failed to capture screenshot of Token{75cf1a6 ActivityRecord{aec5f01 u0 TestApp/md5e91def38f862194d4028772de9f25d90.MainActivity t33 f}} appWin=Window{92ae793 u0 Starting TestApp} drawState=4
04-06 06:15:16.829   257   257 I Zygote  : Process 15807 exited due to signal (11)
04-06 06:15:16.902   615  1582 I ActivityManager: Process TestApp (pid 15807) has died
04-06 06:15:16.902   615  1582 D ActivityManager: cleanUpApplicationRecord -- 15807
04-06 06:15:16.976   615   636 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@a8d053a attribute=null, token = android.os.BinderProxy@598eb0d

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
