### ISSUE TITLE
ZXing doesn't seem to work on iOS 11

### ISSUE THREAD

**Issue by Project4MobileDev** [Redth/ZXing.Net.Mobile#616]
What is the latest version of iOS/Xcode that ZXing will work with? It was working when built with Xcode 7.4 but building with Xcode 8 onwards causes the app to crash. I wanted to check what the latest version of iOS/Xcode ZXing is compatible with so that I can confirm whether it's a problem with ZXing or something I'm doing wrong. We're currently trying to create an iOS 11 build of our app with Xcode 9. Thanks!

**Comment by alanspires** [comment]
I've tested iOS 11 and it works. #590 might be relevant to you.

**Comment by davidglassborow** [comment]
Check your Xcode device logs: 

Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

I added that and it all worked fine

**Comment by brundaged** [comment]
Had the same issue and fixed it with this:

https://stackoverflow.com/questions/39465687/nscamerausagedescription-in-ios-10-0-runtime-crash

**Comment by Redth** [comment]
Yup need permissions. Latest nuget should be fine on ios11

**Comment by aphex3k** [comment]
#590 was closed referencing this ticket but they seem not at all related...
