### ISSUE TITLE
ZXingScannerFragment not working

### ISSUE THREAD

**Issue by ViggoL** [Redth/ZXing.Net.Mobile#761]
The sample provided in the Git repo is not working either. The console output does however say "Barcode found", only that ZXing doesn't react to any results.

To reproduce, download the samples and test run the fragment scanner.

**Comment by Goncharuk-Nikita** [comment]
Yes, I also create my scanner activity scanner, and when I start scanning, then nothing happens when I read the QR-code

**Comment by ooikengsiang** [comment]
This issue was long ago.
If anyone come across this, the workaround is to add
SupportFragmentManager.ExecutePendingTransactions() right after SupportFragmentManager commit to force OnCreateView in fragement to execute correct in order to initialize the scanner correctly.
Source: [](https://github.com/Redth/ZXing.Net.Mobile/pull/638)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
