### ISSUE TITLE
UnauthorizedAccessException when denying camera access

### ISSUE THREAD

**Issue by aspernol** [Redth/ZXing.Net.Mobile#794]
Hello,

I'm using ZXingScannerView in my app. When I push the button which opens the page containing that control a popup appears asking for camera permissions (Camera permissions are set in the visual studio project file for the android app).
When I accept the permissions everything runs fine, but when I deny it the app crashes with an UnauthorizedAccessException.
On the page I simply added the control:
`<qr:ZXingScannerView
            x:Name="ScannerView"
            HorizontalOptions="FillAndExpand"
            OnScanResult="HandleScannerOnResultEvent"
            VerticalOptions="FillAndExpand" />`

In the `MainActivity.OnCreate` I'm doing the following:
`            Platform.Init();
            MobileBarcodeScanner.Initialize(Application);
`
and also in the `MainActivity`:
`        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
`
The last lines of the call stack are:
01-09 11:15:58.521 D/ZXing.Net.Mobile( 3973): System.NullReferenceException: Object reference not set to an instance of an object.
01-09 11:15:58.521 D/ZXing.Net.Mobile( 3973):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x0001e] in <819b29aa6d91462699e19a679be55a44>:0 

I'm using ZXing v2.4.1.
Android: several phones and tablets running Android version 6.0.1 and 8.0

Have I missed something in my implementation? Since the ScannerView control forces the popup and waits for the result as well I'm expecting that it will be handled there. Or do I have to do the check in advance before instantiating the control? But the projects main page says that ZXing handles the permission request for me.

**Comment by HeikkiDev** [comment]
Same issue here. As workaround I wrote my own check and request camera permission service and I use it before open the scanner page.

I'll fork this repository and try to help with this issue.

**Comment by Maxallica** [comment]
Still reproducible.

ZXing.Net.Mobile: 2.4.1
ZXing.Net.Mobile.Forms: 2.4.1

**Comment by manusanudo** [comment]
Same issue here using ZXingScannerPage.

**Comment by ioiooi** [comment]
Same. Even using the samples provided in this repository causes the `UnauthorizedAccessException` to be thrown when denying access to the camera.

After further investigating this behaviour my colleagues and I found that [this line in the `PermissionHandler.cs`](https://github.com/Redth/ZXing.Net.Mobile/blob/1c7dacfce61c2a3f7920289bfd38b623bbaa7120/Source/ZXing.Net.Mobile.Android/PermissionsHandler.cs#L145) is the cause. The message is kinda misleading in that it always says that permission was not found in the `AndroidManifest.xml` even though it is and the actual reason is simply the User denying access.

Changing:
```cs
if (!IsPermissionInManifest(context, permission) || !IsPermissionGranted(context, permission))
```
to
```cs
if (!IsPermissionInManifest(context, permission))
```

Fixes the issue for our use case.
Mind you the application still crashes when the camera permission is not present in the manifest.xml.

But the behaviour after changing the if statement is the following:
User opens the ScanView or Activity and gets asked for the camera permission. If the User denies than the screen will be black/white whatever. If the User navigates back and forth will be asked again until the User accepts or checks 'dont ask again' and denies.

**Comment by ChrisTTian667** [comment]
Nobody is maintaining this library anymore?

**Comment by Redth** [comment]
3.0.0 changes this behaviour.  Now just a black screen appears instead of the exception.

**Comment by nikossaperas** [comment]
For anyone still having this issue, I used version 3.0.0 (in prerelease in the time of writing) and for the problem with the black screen  that @Redth mentions above, the only thing I currently can think of and seems to work is to handle the Camera request permission manually(using Xamarin Essentials). That is, in the button click that will trigger the scanner I used the code below - just in case someone needs a workaround.

                                                                var status = await Permissions.CheckStatusAsync<Permissions.Camera>();
								if(status != PermissionStatus.Granted)
								{
									status = await Permissions.RequestAsync<Permissions.Camera>();
								}
								if (status != PermissionStatus.Granted)
									return;
								MobileBarcodeScanner.Initialize(this.Activity.Application);
								var scanner = new MobileBarcodeScanner();
