### ISSUE TITLE
Scanning View is a little tweak/squeezed on Android devices

### ISSUE THREAD

**Issue by SunshineSpring666** [Redth/ZXing.Net.Mobile#903]
After calling await scanner.Scan(options);  I got a squeezed camera view. 
I tried it on several android devices but they all look that way. Are there any workaround or options to fix this?
Thanks.
![微信图片_20200521182857](https://user-images.githubusercontent.com/42401603/82550583-595c3600-9b91-11ea-909f-3299242a301b.jpg)

**Comment by nitewulf** [comment]
Hey sunshine,

I just submitted a PR that calculates a more accurate display resolution.  It's here:
https://github.com/Redth/ZXing.Net.Mobile/pull/906

It still won't be perfect because of how long the phone is, but it will pick a resolution that is closer to the aspect ratio of that surface view.

Ideally, the camera preview should be zoomed in and cropped a bit.  Or, scaled down to fit with black bars on the top/bottom.  And make both options configurable.  Unfortunately, I couldn't figure out how to do either of those :(  Otherwise I think my PR is the best approach at the moment.

**Comment by SunshineSpring666** [comment]
Thanks for replying. I'll check the thread later.

Best regards,
Sunshine
